packages/specification/examples/GetMyPrescriptions/Bundle/success-multiple.json
packages/specification/prescriptionsforpatients.yaml

:exclamation:**DO NOT MERGE**:exclamation: 
This is not integrating into our pipeline; this is just writing a schema that we will send to the NHS App team manually

AEA-3364 Update GetMyPrescriptions OAS file to include a multiple prescription example

---

cloudformation/ci_resources.yml
packages/spineClient/src/status.ts
sandbox_template.yaml
template.yaml
template_splunk_firehose.yaml

- Enables versioning on splunk bucket
- Fixes filterpattern for cloudwatch subscriptions so all log events go to splunk
- log calls to spine in status lambda

AEA-3446 enable versioning on splunk bucket

---

cloudformation/management_route53.yml

**Remove items from this list if they are not relevant. Remove this line once this has been done**
- :exclamation: Breaking Change
- :robot: Operational or Infrastructure Change
- :sparkles: New Feature
- :warning: Potential issues that might be caused by this change
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**

Added prod hosted zone

---

.github/workflows/pull_request.yml

Use lowercase stack names for pull requests

use lower case stack names for pull requests

---

packages/middleware/src/index.js
packages/middleware/tests/index.test.js

**Remove items from this list if they are not relevant. Remove this line once this has been done**
Corrects meta.lastUpdated to be an ISO datetime string rather than unix epoch time

AEA-3620 correct lastUpdated in error response

---

.github/workflows/sam_release_code.yml
Makefile
SAMtemplates/splunk_firehose_resources.yaml
packages/splunkProcessor/src/helpers.js
packages/splunkProcessor/src/splunkProcessor.js
packages/splunkProcessor/tests/putRecordsToFirehoseStream.test.js
packages/splunkProcessor/tests/putRecordsToKinesisStream.test.js
packages/splunkProcessor/tests/reingestRecordBatches.test.js

- Updates the splunk processor lambda to use the aws powertools logger.
- Updates some log messages to make them better fit the json format.
- Updates pipeline to pass in required env vars to splunkProcessor

AEA-3447:  Add logging framework to splunk processor

---

.github/workflows/dependabot_auto_approve_and_merge.yml

**Remove items from this list if they are not relevant. Remove this line once this has been done**
Use PAT for automerge

use PAT for automerge

---

pyproject.toml

Force version bump to test release lambda 

AEA-3701 test lambda release notes

---

.github/workflows/release.yml

AEA-3661 fix typo in var name in workflow

---

.github/workflows/create_confluence_release_notes.yml
.github/workflows/release.yml

- adds pause step for rc int release notes
- corrects tags for rc int release notes

AEA-3661 fix int release workflow

---

.github/workflows/create_confluence_release_notes.yml
.github/workflows/release.yml

AEA-3661 fix int release

---

.github/workflows/create_confluence_release_notes.yml

- fix normal int release notes

AEA-3661 fix int release notes

---

.github/workflows/create_confluence_release_notes.yml

fix int release notes

---

.github/workflows/dependabot_auto_approve_and_merge.yml

- use github app for approving dependabot pull requests

use app for approving dependabot pull requests

---

SAMtemplates/lambda_resources.yaml

- force creation of a new managed policy resource rather than trying to change inline policy to a managed one

force creation of managed policy in lambda resources

---

.github/workflows/quality_checks.yml
packages/serviceSearchClient/src/live-serviceSearch-client.ts
packages/serviceSearchClient/tests/live-serviceSearch-client.test.ts
packages/spineClient/src/live-spine-client.ts

- safely get headers to calculate duration of external calls

test failure

---

.github/workflows/release.yml

- show the release tag on the github run for releases so we can easily identify what release it is for

add release tag to github run summary

---

.github/scripts/delete_stacks.sh

**Remove items from this list if they are not relevant. Remove this line once this has been done**
Fixed bug spotted by Ant. Introduced by double quoting in array assignment. Introduced as part of [AEA-3622](https://nhsd-jira.digital.nhs.uk/browse/AEA-3622)

Fix delete_old_cloudformation_stacks script - Part Deux

---

.devcontainer/devcontainer.json
packages/getMyPrescriptions/src/getMyPrescriptions.ts
packages/getMyPrescriptions/src/responses.ts
packages/getMyPrescriptions/src/utils.ts
packages/getMyPrescriptions/tests/test-handler.test.ts

Adds timeout to lambda and spine callout.

[AEA-3862] Reduce PfP API Timeout

---

Makefile
package-lock.json
packages/getMyPrescriptions/package.json
packages/statusLambda/package.json

- update get-secrets to v1.0.189-alpha
- update eps-spine-client to 2.0.3

update common libraries 24 April 2024

---

Makefile
README.md
package-lock.json
packages/getMyPrescriptions/package.json
packages/statusLambda/package.json

Updates common libraries
- :robot: Operational or Infrastructure Change
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**

Update common libraries 01052024

---

.github/workflows/pull_request.yml
Makefile
SAMtemplates/apis/main.yaml
SAMtemplates/main_template.old.yaml
SAMtemplates/main_template.yaml
SAMtemplates/sandbox_template.yaml

- :robot: Operational or Infrastructure Change
- Parameterised truststore file

Fix: [AEA-3877]  - Fix clashing truststore files

---

.github/workflows/release.yml

- fix int sandbox truststore file

Fix: [AEA-0000] - really fix sandbox truststore file this time

---

.github/workflows/release.yml

- do not get status updates in any environment except dev

Fix: [AEA-000] - do not get status updates except for dev

---

.github/workflows/release.yml

- fix name of sandbox stacks in int

Fix: [AEA-0000] - fix name of sandbox stack in int

---

.github/workflows/release.yml

- enable get status update in qa environment

Fix: [AEA-0000] - enable get status update in qa

---

Makefile
README.md
postman/prescriptions_for_patients.postman_collection.json

- update postman collection
- fix sam-sync

Docs: [AEA-0000] - update postman collection

---

Makefile
package-lock.json
packages/getMyPrescriptions/package.json
packages/statusLambda/package.json

- update get_secrets and spine_client

Update: [AEA-0000] - update get_secrets and spine_client

---

Makefile
package-lock.json
packages/getMyPrescriptions/package.json
packages/statusLambda/package.json

Package updates per Triage Rota.

Upgrade: [AEA-0000] - Package updates

---

Makefile
package-lock.json
packages/getMyPrescriptions/package.json
packages/statusLambda/package.json

Upgrades get-secrets to v1.0.313, and spine client to v2.0.12

Upgrade: [AEA-0000] - Upgrades Common Libraries

---

SECURITY.md

Docs: [AEA-4305] - add security.md

---

Makefile
package-lock.json
packages/getMyPrescriptions/package.json
packages/statusLambda/package.json

Upgrade: [AEA-0000] - Updating common libraries

---

.github/workflows/ci.yml
.github/workflows/release.yml

- get correct tag when creating a release

Fix: [AEA-0000] - fix getting version tag in release

---

.github/workflows/release.yml
README.md

- fix formatting on readme
- remove unused output on release workflow

Fix: [AEA-0000] - tidy up readme and release workflow

---

Makefile

- always get latest get secrets layer

Fix: [AEA-0000] - auto get latest get secrets layer

---

.github/workflows/ci.yml
.github/workflows/quality_checks.yml
.github/workflows/release.yml
.github/workflows/sam_package_code.yml
README.md
package-lock.json
packages/getMyPrescriptions/package.json
packages/getMyPrescriptions/src/getMyPrescriptions.ts
packages/getMyPrescriptions/tests/status.test.ts
packages/getMyPrescriptions/tests/statusUpdate.test.ts
packages/getMyPrescriptions/tests/test-handler.test.ts
packages/statusLambda/package.json
packages/statusLambda/src/statusLambda.ts

- fix casing for spine client dependency so dependabot picks up changes

Fix: [AEA-0000] - fix casing for spine client dependency

---

.github/workflows/release.yml
.github/workflows/sam_release_code.yml

- parameterize running regression test
- do not run regression tests in int-sandbox and prod

Fix: [AEA-0000] - parameterize running regression test

---

.github/scripts/get_current_dev_tag.sh
.github/scripts/get_target_deployed_tag.sh

Docs: [AEA-0000] - fix getting tag for release notes generation

---

SAMtemplates/alarms/main.yaml
SAMtemplates/main_template.yaml

- :sparkles: New Feature
Adds NPPTS Slack Alerts

New: [AEA-4488] - Adds NPPTS Slack Alerts 

---

.gitallowed
.github/workflows/run_regression_tests.yml
scripts/run_regression_tests.py

- show links to reports on test failures
- generic script that can be run from github or azure
- run from tag

Chore: [AEA-0000] - update run regression

---

.github/workflows/ci.yml
.github/workflows/combine-dependabot-prs.yml
.github/workflows/delete_old_cloudformation_stacks.yml
.github/workflows/dependabot_auto_approve_and_merge.yml
.github/workflows/pr-link.yml
.github/workflows/pr_title_check.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.github/workflows/run_regression_tests.yml
.github/workflows/sam_package_code.yml
.github/workflows/sam_release_code.yml

- pin ubuntu used by gihub runner

Fix: [AEA-0000] - pin ubuntu used by github runner

---

scripts/run_regression_tests.py

- use latest regression test pack

Fix: [AEA-0000] - use latest regression test pack

---

.github/scripts/release_code.sh
.github/workflows/sam_release_code.yml

- add more cloudformation tags

Fix: [AEA-0000] - add more cloudformation tags
